### ISSUE TITLE
Internal Server error; "sha1(): Argument #1 ($string) must be of type string, null given"

### ISSUE THREAD

**Issue by t0mcat1337** [eid-login/eid-login-nextcloud#12]
After having setup the eid app, connecting it successfully to "skydentity.de", and linked my NC account successfully with it
the login to Nextcloud with eID fails with Nextcloud saying "Internal Server error".

Steps done:
1) Choose "eID-Login" at NC Login screen
2) Successful identify via German eID card to skydentity using Smartphone, NFC and "Ausweisapp2"
3) NC errors out with "Internal Server error".

This is in NC Log:
```
[index] Fehler: Exception: sha1(): Argument #1 ($string) must be of type string, null given in file '/var/www/html/lib/private/Authentication/Token/PublicKeyTokenProvider.php' line 116 at <<closure>>

0. /var/www/html/lib/private/AppFramework/App.php line 183
   OC\AppFramework\Http\Dispatcher->dispatch(["OCA\\EidLogin\ ... "], "resume")
1. /var/www/html/lib/private/Route/Router.php line 315
   OC\AppFramework\App::main("OCA\\EidLogin\\ ... r", "resume", ["OC\\AppFramewo ... "], ["eidlogin.eid.resume"])
2. /var/www/html/lib/base.php line 1055
   OC\Route\Router->match("/apps/eidlogin/eid/resume/%5Bid%7D")
3. /var/www/html/index.php line 36
   OC::handleRequest()

Caused by:

TypeError: sha1(): Argument #1 ($string) must be of type string, null given at <<closure>>

 0. /var/www/html/lib/private/Authentication/Token/PublicKeyTokenProvider.php line 116
    sha1("*** sensitive parameters replaced ***")
 1. /var/www/html/lib/private/Authentication/Token/Manager.php line 69
    OC\Authentication\Token\PublicKeyTokenProvider->generateToken("*** sensitive parameters replaced ***")
 2. /var/www/html/lib/private/User/Session.php line 686
    OC\Authentication\Token\Manager->generateToken("*** sensitive parameters replaced ***")
 3. /var/www/html/apps/eidlogin/lib/Service/EidService.php line 590
    OC\User\Session->createSessionToken("*** sensitive parameters replaced ***")
 4. /var/www/html/apps/eidlogin/lib/Controller/EidController.php line 153
    OCA\EidLogin\Service\EidService->processSamlResponseData("*** sensitive parameters replaced ***", "ahne5apJBXGo5BuT3iyYexU6")
 5. /var/www/html/lib/private/AppFramework/Http/Dispatcher.php line 230
    OCA\EidLogin\Controller\EidController->resume("ahne5apJBXGo5BuT3iyYexU6")
 6. /var/www/html/lib/private/AppFramework/Http/Dispatcher.php line 137
    OC\AppFramework\Http\Dispatcher->executeController(["OCA\\EidLogin\ ... "], "resume")
 7. /var/www/html/lib/private/AppFramework/App.php line 183
    OC\AppFramework\Http\Dispatcher->dispatch(["OCA\\EidLogin\ ... "], "resume")
 8. /var/www/html/lib/private/Route/Router.php line 315
    OC\AppFramework\App::main("OCA\\EidLogin\\ ... r", "resume", ["OC\\AppFramewo ... "], ["eidlogin.eid.resume"])
 9. /var/www/html/lib/base.php line 1055
    OC\Route\Router->match("/apps/eidlogin/eid/resume/%5Bid%7D")
10. /var/www/html/index.php line 36
    OC::handleRequest()


```
NC Version: 26.0.0 running in Kubernetes
eID App Version:  1.0.12

BTW:
-> the linked account comes from an LDAP
-> it has TwoFactor (via OTP or NC Notifications) activated

Any idea?
Thx in advance

**Comment by ecmrauh** [comment]
Sorry for the delay, but it took me some time to setup a test environment to reproduce the error. The problem is not the two-factor authentication with OTP, but the usage of the plugin "LDAP user and group backend" together with the eidlogin plugin. I'll try to investigate the root cause of the issue and let you know as soon as there are any updates on this.

**Comment by ecmrauh** [comment]
I found [this commit](https://github.com/nextcloud/server/commit/6881d2f2f15976514cc52d6ea49ff09c5bb81d2b) which probably fixes the error `Exception: sha1(): Argument #1 ($string) must be of type string, null given` as it introduces an additional check before calling the sha1 function.

This fix is present since Nextcloud version 26.0.1 (see [26.0.0](https://github.com/nextcloud/server/blob/v26.0.0/lib/private/Authentication/Token/PublicKeyTokenProvider.php#L116) vs. [26.0.1](https://github.com/nextcloud/server/blob/v26.0.1/lib/private/Authentication/Token/PublicKeyTokenProvider.php#L116)).

After changing the line mentioned in the commit above, I was not able to reproduce the error. So please try to update Nextcloud to version 26.0.1 or make sure to replace line 116 in the [PublicKeyTokenProvider.php](https://github.com/nextcloud/server/blob/v26.0.1/lib/private/Authentication/Token/PublicKeyTokenProvider.php#L116).

**Comment by t0mcat1337** [comment]
I just updated NC to 26.0.1 and indeed, now everything works fine .... was able to connect my account to the eID and also can login with it.

Thx a lot :)

**Comment by ecmrauh** [comment]
I'm glad it worked  and thanks for your feedback!
