### ISSUE TITLE
NC 22.2.3: Verknüpfung der eID schlägt fehl

### ISSUE THREAD

**Issue by Geestbiker** [eid-login/eid-login-nextcloud#7]
Moin,

ich möchte die eID-Funktion (v1.0.7) auf meiner NC 22.2.3 einrichten. Wenn ich nun meinen Ausweis/eID in meinem Benutzerkonto verknüpfen möchte erhalte ich im Protokoll folgende Meldungen:

> [eidlogin] Info: processResponseData found errors or user not authenticated - errors:Array ([0] => invalid_response), saml status msg: 
>
>GET /apps/eidlogin/eid/resume/%5Bid%7D?id=[ID]
>from [IP-Adresse] by [USER] at 2021-12-29T16:33:58+01:00

und

> [eidlogin] Info: processResponseData last error reason: The response was received at http://[meine.domain]:82/apps/eidlogin/saml/acs instead of https://[meine.domain]/apps/eidlogin/saml/acs
>
>GET /apps/eidlogin/eid/resume/%5Bid%7D?id=[ID]
>from [IP-Adresse] by [USER] at 2021-12-29T16:33:58+01:00

Stuzig macht mich die Antowort an Port 82, dazu konnte ich jedoch keine weiteren Informationen finden.

Nutze ich die Test-Funktion des Anbieters SkiDenty werde ich erfolgreich auf das Dashboard meines Administrator-Accounts weitergeleitet, wenn dieser angemeldet ist. Wenn nicht, lande ich auf der Login-Seite. Im Protokoll erhalte ich dann zusätzlich folgende 2 Meldungen:

> [eidlogin] Error: error creating SAML Response for user : missing inResponseTo Attribute in SAML Response
>
>POST /apps/eidlogin/saml/acs
>from  [IP-Adresse] at 2021-12-29T16:42:58+01:00

und 

> [eidlogin] Error: error creating SAML Response for user : missing inResponseTo Attribute in SAML Response
>
>POST /apps/eidlogin/saml/acs
>from  [IP-Adresse] at 2021-12-29T16:43:43+01:00

Bei der Einrichtung habe ich mich an das Tutorial auf der Website des Anbieters gehalten: [https://eid.services/Nextcloud-final.mp4](url)
Ich benutze die AusweisApp2 auf PC und iOS.

Bin für Lösungshinweise dankbar.

**Comment by ecmrauh** [comment]
Hallo und sorry für die (urlaubsbedingt) späte Antwort!

Kann es sein, dass das Nextcloud hinter einem Reverse Proxy / Load Balancer betrieben wird? In diesem Fall könnte es sein, dass Nextcloud nicht die korrekten Werte für das Auslesen des verwendeten Protokolls bzw. Ports verwendet. Das würde ggf. die URL `http://[meine.domain]:82` erklären. Die entscheidende Fehlermeldung ist diese hier:

`The response was received at http://[meine.domain]:82/apps/eidlogin/saml/acs instead of https://[meine.domain]/apps/eidlogin/saml/acs`

Das bedeutet, dass die bei SkIDentity hinterlegte URL (also die, wohin die SAML Response geschickt wird) nicht mit der von Nextcloud ermittelten URL übereinstimmt.

Damit Nextcloud die korrekten Werte für Protokoll und Port "sieht", muss man die entsprechenden Header setzen. Bei Apache2 kann das z.B. so erfolgen:

```
RequestHeader set X-Forwarded-Proto "%{REQUEST_SCHEME}s"
RequestHeader set X-Forwarded-Port  "%{SERVER_PORT}s"
```

Für nginx gibt es sicherlich vergleichbare Einstellungen. Zudem können diese Werte auch in der Konfigurationsdatei von Nextcloud überschrieben werden, [siehe hier](https://docs.nextcloud.com/server/latest/admin_manual/configuration_server/reverse_proxy_configuration.html#overwrite-parameters).

**Comment by Geestbiker** [comment]
Danke für die Rückmeldung.

Ja, die Nextcloud läuft hinter einem nginx reverse proxy. Intern lauscht der nextcloud-vHost auf Port 82 und das Gateway auf 80 und 443.

Im proy-pass-block des Gateway habe ich folgende Zeilen ergänzt, damit funktioniert es nun wie gewünscht:
`proxy_set_header X-Forwarded-Proto $scheme;`
`proxy_set_header X-Forwarded-Port $server_port;`

Wie sähe der Eintrag in der nextcloud-config aus? Da tue ich mich zugegebenermaßen schwer aus der verlinkten Hilfe schlau zu werden.

**Comment by ecmrauh** [comment]
Die Parameter können in der bestehenden Konfigurationsdatei von Nextcloud in `config/config.php` ergänzt werden, also z.B.:

```php
<?php
  $CONFIG = array (
    // ...
    'overwritehost' => 'my-hostname',
    'overwriteprotocol' => 'https',
    // ...
);
```
Erklärungen und Beispiele zu den Parametern finden sich auch in der [Beispielkonfiguration](https://github.com/nextcloud/server/blob/master/config/config.sample.php#L499).
